/* ====================================================
   |                                                  |
   |                  PLC Simulation                  |
   |                                                  |
   |     (c) Copyright 1996,97,98  Rodrigo Alonso     |
   |                                                  |
   ===================================================|  */
//loader.cpp
//
// Reading of program files (.epg, generated by ACTSIP-E) and external wiring
// files (.sda). Adapted from plc::procesar_archivo and plc::procesar_archivo2
// of the original simulator.
//
// Unlike the original, everything the simulation uses as an index is
// validated, CR/LF line endings are accepted and errors report the line
// number.

#include <ctype.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "engine.h"

namespace plcsim_detail {

//----------------------------------------------------------------------------
// Line reader over a memory buffer
struct reader {
  const char *p, *end;
  unsigned line;
};

struct line_t {
  const char *s;
  size_t n;
};

// Gets the next line, without the line ending or trailing blanks.
static bool next_line(reader &r, line_t &li)
{
  if (r.p >= r.end) return false;
  const char *begin=r.p;
  while (r.p < r.end && *r.p != '\n') r.p++;
  li.s=begin;
  li.n=r.p-begin;
  if (r.p < r.end) r.p++;  // skip the '\n'
  while (li.n>0 && isspace((unsigned char)li.s[li.n-1])) li.n--;
  r.line++;
  return true;
}

static bool is_marker(const line_t &li, const char *marker)
{
  return li.n==strlen(marker) && memcmp(li.s,marker,li.n)==0;
}

// Advances past the line 'marker'. Returns false if not found.
static bool seek_marker(reader &r, const char *marker)
{
  line_t li;
  while (next_line(r,li))
    if (is_marker(li,marker)) return true;
  return false;
}

// Fixed width numeric field.
static bool number_field(const line_t &li, size_t pos, size_t len, int base,
                         unsigned *value)
{
  unsigned v=0;

  if (pos+len > li.n) return false;
  for (size_t i=0; i<len; i++)
  {
    int c=tolower((unsigned char)li.s[pos+i]),d;
    if (c>='0' && c<='9') d=c-'0';
      else if (c>='a' && c<='f') d=c-'a'+10;
      else return false;
    if (d>=base) return false;
    v=v*base+d;
  }
  *value=v;
  return true;
}

// Fixed width text field, without trailing blanks. "-" is an empty field.
static void text_field(const line_t &li, size_t pos, size_t len, char *dest)
{
  size_t i=0;

  if (pos < li.n)
    for (; i<len && pos+i<li.n; i++) dest[i]=li.s[pos+i];
  while (i>0 && dest[i-1]==' ') i--;
  dest[i]='\0';
  if (strcmp(dest,"-")==0) dest[0]='\0';
}

static int fail(char *error, size_t error_size, int code,
                const char *format, ...)
{
  va_list ap;
  va_start(ap,format);
  vsnprintf(error,error_size,format,ap);
  va_end(ap);
  return code;
}

unsigned operand_width(unsigned function)
{
  switch (function)
  {
    case 0: case 1: case 23: case 50:
      return 1;
    case 10: case 11: case 12: case 15: case 16: case 17: case 18: case 19:
    case 21: case 61: case 62: case 63:
      return 2;
    case 20: case 22:
      return 16;
  }
  return 0;
}

//----------------------------------------------------------------------------
// Program file. Loads all the tables used by the simulation.
// The program is not checked for syntax, since it is assumed to have been
// created with the ACTSIP-E software.
//
// Format of a program line (14 characters):
//   NNNNOO-xxxAAAA   instruction: OO opcode (hex, +0x80 for a timer operand)
//   NNNNxxPFFxAAAA   function:    FF number (decimal), P=='3' dot function
//   NNNN step number, AAAA operand (hex)
// The original replacement of STR by STR AND / STR OR (etc.) is not done
// here: it was only needed for the ladder listing.
int parse_program(const char *data, size_t size, program *prog,
                  char *error, size_t error_size)
{
  reader r={data,data+size,0};
  line_t li;
  unsigned opcode,operand,n;

//----------------------------------------------------------------------------
// HEADER.
  if (!seek_marker(r,"PGM-START"))
    return fail(error,error_size,PLCSIM_ERR_FORMAT,
                "Invalid file format: missing PGM-START");
  for (int i=0; i<2; i++)
    if (!next_line(r,li))
      return fail(error,error_size,PLCSIM_ERR_FORMAT,
                  "Invalid file format: missing PGM-END");

//----------------------------------------------------------------------------
// PGM-START .. PGM-END. Program steps.
  n=0;
  while (true)
  {
    if (!next_line(r,li))
      return fail(error,error_size,PLCSIM_ERR_FORMAT,
                  "Invalid file format: missing PGM-END");
    if (is_marker(li,"PGM-END")) break;
    if (n>=PLCSIM_MAX_STEPS)
      return fail(error,error_size,PLCSIM_ERR_FORMAT,
                  "line %u: the program exceeds %u steps",
                  r.line,PLCSIM_MAX_STEPS);
    step &st=prog->steps[n];
    if (li.n<14 || !number_field(li,10,4,16,&operand))
      return fail(error,error_size,PLCSIM_ERR_FORMAT,
                  "line %u: invalid instruction",r.line);
    if (li.s[6] == '-')    // INSTRUCTION
    {
      if (!number_field(li,4,2,16,&opcode))
        return fail(error,error_size,PLCSIM_ERR_FORMAT,
                    "line %u: invalid opcode",r.line);
      st.flags=F_INSTRUCTION;
      if (opcode>128)  // operand type
      {
        opcode-=128;
        st.flags|=F_TIMER_OPERAND;
      } else st.flags|=F_RELAY_OPERAND;
      switch (opcode)
      {
        case PLCSIM_OP_ORG: case PLCSIM_OP_ORG_NOT:
        case PLCSIM_OP_STR: case PLCSIM_OP_STR_NOT:
        case PLCSIM_OP_AND: case PLCSIM_OP_AND_NOT:
        case PLCSIM_OP_OR:  case PLCSIM_OP_OR_NOT:
        case PLCSIM_OP_OUT: case PLCSIM_OP_OUT_NOT:
          if (operand >= ((st.flags & F_TIMER_OPERAND) ? PLCSIM_TIMER_COUNT
                                                       : PLCSIM_MEMORY_SIZE))
            return fail(error,error_size,PLCSIM_ERR_FORMAT,
                        "line %u: operand %X out of range",r.line,operand);
      }
      st.opcode=opcode;
      st.operand=operand;
    } else           // FUNCTION
      {
        if (!number_field(li,7,2,10,&opcode))
          return fail(error,error_size,PLCSIM_ERR_FORMAT,
                      "line %u: invalid function number",r.line);
        st.flags=F_FUNCTION;
// dot functions (0. to 9.) are mapped to numbers 110 to 119.
        if (li.s[6]=='3') opcode+=110;
// so that after start-up the input must go back to rest before an edge is
// detected
        if (opcode==0 || opcode==1) st.flags|=F_LOCKED;
        st.opcode=opcode;
        if (opcode>=110 && opcode<=119)
        {
          uint16_t bcd;
          if (bin_to_bcd(operand,&bcd)) operand=bcd;
        }
        unsigned width=operand_width(opcode);
        if (width && operand+width > PLCSIM_MEMORY_SIZE)
          return fail(error,error_size,PLCSIM_ERR_FORMAT,
                      "line %u: operand %X out of range",r.line,operand);
        st.operand=operand;
      }
    n++;
  }
  prog->step_count=n;
  reader after_program=r;

//----------------------------------------------------------------------------
// IO-START .. IO-END. Names and comments of the inputs / outputs.
//   AAAAnnnnnnnnnnccccccccccccccccccccccccccccccxx
//   AAAA address (hex), n name, c comment
  if (seek_marker(r,"IO-START"))
  {
    next_line(r,li);  // range
    while (true)
    {
      if (!next_line(r,li))
        return fail(error,error_size,PLCSIM_ERR_FORMAT,
                    "Invalid file format: missing IO-END");
      if (is_marker(li,"IO-END")) break;
      if (li.n==0) continue;
      if (!number_field(li,0,4,16,&n) || n>=PLCSIM_MEMORY_SIZE)
        return fail(error,error_size,PLCSIM_ERR_FORMAT,
                    "line %u: invalid I/O address",r.line);
      text_field(li,4,10,prog->io[n].name);
      text_field(li,14,30,prog->io[n].comment);
    }
  }

//----------------------------------------------------------------------------
// TC-START .. TC-END. Timers / counters.
//   NNNnnnnnnnnnnccccccccccccccccccccccccccccccVVVVVxT
//   NNN number (octal), n name, c comment,
//   T=='5' timer with preset VVVVV, else counter with preset VVVV (decimal)
  r=after_program;
  if (seek_marker(r,"TC-START"))
  {
    next_line(r,li);  // range
    while (true)
    {
      if (!next_line(r,li))
        return fail(error,error_size,PLCSIM_ERR_FORMAT,
                    "Invalid file format: missing TC-END");
      if (is_marker(li,"TC-END")) break;
      if (li.n==0) continue;
      if (!number_field(li,0,3,8,&n) || n>=PLCSIM_TIMER_COUNT)
        return fail(error,error_size,PLCSIM_ERR_FORMAT,
                    "line %u: invalid timer number",r.line);
      text_field(li,3,10,prog->timers[n].name);
      unsigned preset;
      bool ok;
      if (li.n>49 && li.s[49]=='5')
      {
        prog->timers[n].is_counter=0;
        ok=number_field(li,43,5,10,&preset);
      } else {
               prog->timers[n].is_counter=1;
               ok=number_field(li,43,4,10,&preset);
             }
      if (!ok)
        return fail(error,error_size,PLCSIM_ERR_FORMAT,
                    "line %u: invalid timer preset",r.line);
      prog->timers[n].preset=preset;
    }
  }
  return PLCSIM_OK;
}

//----------------------------------------------------------------------------
// External wiring file. Simulates the wiring outside the PLC. It is made of
// tokens separated by blanks or commas, with // and /* */ comments, in any
// combination of upper and lower case. The keywords are in Spanish:
//
//   [temporizadores]  output time input ...   (when output is ON (OFF if
//                                              negative) for 'time'
//                                              centiseconds, sets input ON
//                                              (OFF if negative))
//   [selectoras]      inicio pos1 pos2 ... fin ...   (selector switches)
//   [link]            presente | ausente             (present | absent)
//   [colores]         address color [locked] ...     (ignored)
//
// Addresses use the external numbering.
#define MAX_TOKEN 20

// Returns false when there are no more tokens.
static bool next_token(reader &r, char *s, bool *too_long)
{
  size_t i=0;

  *too_long=false;
// skip comments, newlines, blanks, tabs and commas
  while (r.p < r.end)
  {
    char c=*r.p;
    if (c=='/' && r.p+1 < r.end && r.p[1]=='/')
    {
      while (r.p < r.end && *r.p!='\n') r.p++;
    } else
    if (c=='/' && r.p+1 < r.end && r.p[1]=='*')
    {
      r.p+=2;
      while (r.p+1 < r.end && !(r.p[0]=='*' && r.p[1]=='/'))
      {
        if (*r.p=='\n') r.line++;
        r.p++;
      }
      r.p=(r.p+1 < r.end) ? r.p+2 : r.end;
    } else
    if (c=='\n')
    {
      r.line++;
      r.p++;
    } else
    if (isspace((unsigned char)c) || c==',' || c=='/') r.p++;
    else break;
  }
  if (r.p >= r.end) return false;
// take the next token
  while (r.p < r.end && !isspace((unsigned char)*r.p) && *r.p!=','
         && *r.p!='/')
  {
    if (i<MAX_TOKEN) s[i++]=tolower((unsigned char)*r.p);
      else *too_long=true;
    r.p++;
  }
  s[i]='\0';
  return true;
}

static bool parse_int(const char *s, long *value)
{
  char *end;

  if (!isdigit((unsigned char)s[s[0]=='-' ? 1 : 0])) return false;
  *value=strtol(s,&end,10);
  return *end=='\0';
}

// Converts an external address into an internal one, keeping the sign.
static long external_to_internal(long ext)
{
  return 16*(ext/20)+(ext%20);
}

int parse_wiring(const char *data, size_t size, wiring *wir,
                 char *error, size_t error_size)
{
  enum { NONE, TIMERS, SELECTORS, LINK, COLORS } section=NONE;
  static const char *colors[]={"verde","rojo","amarillo","azul","celeste",
                               "violeta","gris"};
  reader r={data,data+size,1};
  char s[MAX_TOKEN+1];
  bool too_long;
  int sections=0;
  long output,delay,input,addr,locked;

  wir->link=-1;
  memset(wir->selector_of,-1,sizeof(wir->selector_of));

// Reads the next numeric token into 'var', or fails.
#define NUMERIC_TOKEN(var) \
  if (!next_token(r,s,&too_long) || too_long || !parse_int(s,&(var))) \
    return fail(error,error_size,PLCSIM_ERR_FORMAT, \
                "line %u: number expected",r.line);
// Converts 'var' into an internal address, or fails.
#define ADDRESS(var) \
  (var)=external_to_internal(var); \
  if (labs(var) >= (long)PLCSIM_MEMORY_SIZE) \
    return fail(error,error_size,PLCSIM_ERR_FORMAT, \
                "line %u: address out of range",r.line);

  while (next_token(r,s,&too_long))
  {
    if (too_long)
      return fail(error,error_size,PLCSIM_ERR_FORMAT,
                  "line %u: token too long",r.line);
    if (s[0]=='[')
    {
      if (strcmp(s,"[temporizadores]")==0) { section=TIMERS; sections|=1; }
      else if (strcmp(s,"[selectoras]")==0) { section=SELECTORS; sections|=2; }
      else if (strcmp(s,"[link]")==0) { section=LINK; sections|=4; }
      else if (strcmp(s,"[colores]")==0) { section=COLORS; sections|=8; }
      else return fail(error,error_size,PLCSIM_ERR_FORMAT,
                       "line %u: unknown section %s",r.line,s);
      continue;
    }
    switch (section)
    {
// Timers
      case TIMERS:
      {
        if (wir->timer_count >= MAX_WIRING_TIMERS)
          return fail(error,error_size,PLCSIM_ERR_FORMAT,
                      "line %u: more than %d timers",r.line,
                      MAX_WIRING_TIMERS);
        if (!parse_int(s,&output))
          return fail(error,error_size,PLCSIM_ERR_FORMAT,
                      "line %u: number expected",r.line);
        ADDRESS(output);
        NUMERIC_TOKEN(delay);
        if (delay<0)
          return fail(error,error_size,PLCSIM_ERR_FORMAT,
                      "line %u: negative time",r.line);
        NUMERIC_TOKEN(input);
        ADDRESS(input);
        wiring_timer &wt=wir->timers[wir->timer_count++];
        wt.output=output;
        wt.delay=delay;
        wt.input=input;
        wt.state=WT_READY;
        break;
      }
// Selector switches
      case SELECTORS:
      {
        if (strcmp(s,"inicio")!=0)
          return fail(error,error_size,PLCSIM_ERR_FORMAT,
                      "line %u: 'inicio' expected",r.line);
        if (wir->selector_count >= MAX_SELECTORS)
          return fail(error,error_size,PLCSIM_ERR_FORMAT,
                      "line %u: more than %d selectors",r.line,
                      MAX_SELECTORS);
        selector &sel=wir->selectors[wir->selector_count];
        while (true)
        {
          if (!next_token(r,s,&too_long) || too_long)
            return fail(error,error_size,PLCSIM_ERR_FORMAT,
                        "line %u: 'fin' expected",r.line);
          if (strcmp(s,"fin")==0) break;
          if (!parse_int(s,&addr))
            return fail(error,error_size,PLCSIM_ERR_FORMAT,
                        "line %u: number expected",r.line);
          ADDRESS(addr);
          if (addr<0 || sel.count>=MAX_SELECTOR_POSITIONS)
            return fail(error,error_size,PLCSIM_ERR_FORMAT,
                        "line %u: invalid selector position",r.line);
          sel.positions[sel.count++]=addr;
          wir->selector_of[addr]=wir->selector_count;
        }
        if (sel.count==0)
          return fail(error,error_size,PLCSIM_ERR_FORMAT,
                      "line %u: selector without positions",r.line);
        wir->selector_count++;
        break;
      }
// Link
      case LINK:
        if (strcmp(s,"presente")==0) wir->link=1;
          else if (strcmp(s,"ausente")==0) wir->link=0;
          else return fail(error,error_size,PLCSIM_ERR_FORMAT,
                           "line %u: 'presente' or 'ausente' expected",
                           r.line);
        break;
// Colors. Only meaningful to the graphical interface: validated and
// discarded.
      case COLORS:
      {
        if (!parse_int(s,&addr))
          return fail(error,error_size,PLCSIM_ERR_FORMAT,
                      "line %u: number expected",r.line);
        addr=external_to_internal(addr);
        if (!next_token(r,s,&too_long))
          return fail(error,error_size,PLCSIM_ERR_FORMAT,
                      "line %u: color expected",r.line);
        size_t c=0;
        while (c<sizeof(colors)/sizeof(colors[0]) && strcmp(s,colors[c])!=0)
          c++;
        if (too_long || c==sizeof(colors)/sizeof(colors[0]))
          return fail(error,error_size,PLCSIM_ERR_FORMAT,
                      "line %u: unknown color",r.line);
        if (addr>=0 && addr<PLCSIM_OUTPUT_BASE)  // inputs: locked flag
          NUMERIC_TOKEN(locked);
        break;
      }
      case NONE:
        return fail(error,error_size,PLCSIM_ERR_FORMAT,
                    "line %u: section expected",r.line);
    }
  }
#undef NUMERIC_TOKEN
#undef ADDRESS
  if (sections==0)
    return fail(error,error_size,PLCSIM_ERR_FORMAT,
                "Invalid file format: no sections");
  return PLCSIM_OK;
}

} // namespace plcsim_detail
